basePath: /
host: localhost:8080
info:
  contact:
    name: l1l1ut1kk
  description: Images management service API in Go using Gin framework.
  license:
    name: Ubuntu 22.04
  title: Gin image Service
  version: "1.0"
paths: {}
swagger: "2.0"
